### ISSUE TITLE
This no longer works

### ISSUE THREAD

**Issue by TheMightyWrath** [danefairbanks/TwitchClipManager#10]
Hey there, it's been many many months since I've been able to get this program to work and now when I try it I get errors like this:
Unhandled exception. System.Exception: [04/11/2021 12:02:09] GetUserInfo failed.
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
   at ClipManager.Program.GetUserInfo(String login)
   --- End of inner exception stack trace ---
   at ClipManager.Program.GetUserInfo(String login)
   at ClipManager.Program.Main(String[] args)

This is after copying the auth code, choosing upper and lower views as 0 and bulk 7 days (which always worked before - last time it worked was back in March 2020).

Is it no longer possible to use this program to mass download clips from Twitch?

**Comment by danefairbanks** [comment]
yeah unfortunately i don't have any time to keep this project going especially with the  functionality built into twitch now itself its defunct.  they also recently took down the endpoints that this relied on.

**Comment by Naniad** [comment]
This video details a way to mass download clips which I find works well https://www.youtube.com/watch?v=iwmBogNVPVU
